server:
  port: 8088
spring:
  datasource: 
      url: jdbc:mysql://localhost:3306/testsave?characterEncoding=utf8&useUnicode=true
      username: root
      password: 12456
      driver-class-name: com.mysql.jdbc.Driver  